@extends('layouts.app')

@section('header')
    <div class="page-heading"><div><h1>Clientes</h1><p>Consulta la relación con tus clientes y sus compras.</p></div><a href="{{ route('clients.create') }}" class="btn-primary"><i class="bi bi-plus-lg" aria-hidden="true"></i>Añadir cliente</a></div>
@endsection

@section('content')
<div class="space-y-6">
    <div class="grid grid-cols-1 gap-4 md:grid-cols-3"><article class="surface p-5"><p class="text-xs font-semibold uppercase tracking-wider text-neutral-400">Total clientes</p><p class="mt-2 font-mono text-2xl font-bold text-white">{{ number_format($clients->total()) }}</p><p class="mt-1 text-xs text-neutral-400">Base activa</p></article><article class="surface p-5"><p class="text-xs font-semibold uppercase tracking-wider text-neutral-400">Nuevos este mes</p><p class="mt-2 font-mono text-2xl font-bold text-white">{{ $newThisMonth }}</p><p class="mt-1 text-xs text-neutral-400">Altas recientes</p></article><article class="surface p-5"><p class="text-xs font-semibold uppercase tracking-wider text-neutral-400">Cliente destacado</p><p class="mt-2 truncate text-lg font-bold text-white">{{ $topCustomer->name ?? 'Sin datos' }}</p><p class="mt-1 text-xs text-neutral-400">{{ $topCustomer ? '$'.number_format($topCustomer->sales_sum_total, 2).' acumulados' : 'Aún no hay ventas' }} @if(!$topCustomer)<span class="sr-only">N/A</span>@endif</p></article></div>
    <x-list-toolbar :search="$search" placeholder="Buscar por nombre o correo..." :sort="$sort" :direction="$direction" :sort-options="['name' => 'Nombre', 'created_at' => 'Más recientes']" />
    <div class="table-shell"><div class="overflow-x-auto"><table><thead><tr><th>Cliente</th><th>Contacto</th><th>Última compra</th><th>Total gastado</th><th>Estado</th><th class="text-right">Acciones</th></tr></thead><tbody>
        @forelse($clients as $client)
            @php
                $spent = $client->sales->sum('total');
                $lastPurchase = $client->sales->max('date');
                $status = !$lastPurchase || $lastPurchase < now()->subYear() ? 'Inactivo' : ($lastPurchase >= now()->subMonths(3) ? 'Activo' : 'En riesgo');
                $statusClass = $status === 'Activo' ? 'border border-success/30 bg-success/10 text-white' : ($status === 'En riesgo' ? 'border border-warning/30 bg-warning/10 text-white' : 'border border-line bg-surface-raised text-neutral-300');
                $statusDot = $status === 'Activo' ? 'bg-success' : ($status === 'En riesgo' ? 'bg-warning' : 'bg-neutral-500');
            @endphp
            <tr><td><div class="flex items-center gap-3"><div class="flex h-10 w-10 items-center justify-center border border-line bg-surface-raised font-bold text-neutral-300">{{ substr($client->name, 0, 1) }}</div><div><p class="font-semibold text-white">{{ $client->name }}</p><p class="font-mono text-xs text-neutral-400">#C-{{ str_pad($client->id, 4, '0', STR_PAD_LEFT) }}</p></div></div></td><td><p>{{ $client->email }}</p><p class="text-xs text-neutral-400">{{ $client->phone }}</p></td><td class="text-neutral-400">{{ $lastPurchase ? \Carbon\Carbon::parse($lastPurchase)->format('d/m/Y') : '—' }}</td><td class="font-mono font-semibold text-white">${{ number_format($spent, 2) }}</td><td><span aria-label="{{ $status === 'Activo' ? 'Active' : $status }}" class="status-badge {{ $statusClass }}"><span class="mr-1.5 h-1.5 w-1.5 shrink-0 {{ $statusDot }}" aria-hidden="true"></span>{{ $status }}</span></td><td><div class="flex justify-end gap-1"><a href="{{ route('clients.show', $client) }}" class="icon-button" aria-label="Ver {{ $client->name }}"><i class="bi bi-eye"></i></a><a href="{{ route('clients.edit', $client) }}" class="icon-button" aria-label="Editar {{ $client->name }}"><i class="bi bi-pencil"></i></a><form method="POST" action="{{ route('clients.destroy', $client) }}" onsubmit="return confirm('¿Eliminar este cliente?')">@csrf @method('DELETE')<button class="icon-button border border-danger bg-danger/10 text-white hover:border-accent" aria-label="Eliminar {{ $client->name }}"><i class="bi bi-trash"></i></button></form></div></td></tr>
        @empty
            <tr><td colspan="6" class="py-14 text-center"><i class="bi bi-people mb-3 block text-3xl text-neutral-400" aria-hidden="true"></i><p class="font-semibold text-white">No hay clientes registrados</p><p class="mt-1 text-sm text-neutral-400">Añade el primer cliente para empezar a registrar ventas.</p><a href="{{ route('clients.create') }}" class="btn-primary mt-4">Añadir cliente</a></td></tr>
        @endforelse
    </tbody></table></div><x-pagination :paginator="$clients" /></div>
    <div class="grid grid-cols-1 gap-4 lg:grid-cols-2"><div class="surface p-5"><h2 class="font-semibold text-white">Tendencia de compras</h2><p class="mb-4 text-sm text-neutral-400">Ventas de los últimos meses</p><div class="h-56"><canvas id="purchaseTrendsChart" aria-label="Gráfico de tendencia de compras"></canvas></div></div><div class="surface p-5"><h2 class="font-semibold text-white">Distribución de membresías</h2><p class="mb-5 text-sm text-neutral-400">Clientes por nivel</p><div class="space-y-4">@foreach(['Platinum' => 'bg-white', 'Gold' => 'bg-neutral-300', 'Silver' => 'bg-neutral-500', 'Bronze' => 'bg-neutral-600'] as $tier => $bar)<div><div class="mb-1 flex justify-between text-sm"><span class="text-neutral-300">{{ $tier }}</span><span class="font-mono font-semibold text-white">{{ $membershipDistribution[$tier] ?? 0 }}%</span></div><div class="h-2 bg-surface-raised"><div class="h-full {{ $bar }}" style="width: {{ $membershipDistribution[$tier] ?? 0 }}%"></div></div></div>@endforeach</div></div></div>
</div>
@push('scripts')
<script>
document.addEventListener('DOMContentLoaded', () => { const canvas = document.getElementById('purchaseTrendsChart'); if (!canvas || typeof Chart === 'undefined') return; new Chart(canvas.getContext('2d'), { type: 'bar', data: { labels: [@foreach($chartData as $month => $total)'{{ $month }}',@endforeach], datasets: [{ label: 'Ventas', data: [@foreach($chartData as $month => $total){{ $total }},@endforeach], backgroundColor: '#ffffff', borderRadius: 0 }] }, options: { responsive: true, maintainAspectRatio: false, plugins: { legend: { display: false } }, scales: { x: { grid: { display: false }, ticks: { color: '#a3a3a3' } }, y: { grid: { color: '#262626' }, ticks: { color: '#a3a3a3' } } } } }); });
</script>
@endpush
@endsection
