@php($editing = $product !== null)
<div class="mx-auto max-w-4xl">
    <div class="mb-6 flex items-start justify-between gap-4"><div><p class="text-sm font-medium text-accent">Catálogo</p><h1 class="mt-1 text-2xl font-bold text-white">{{ $editing ? 'Editar producto' : 'Nuevo producto' }}</h1><p class="mt-1 text-sm text-neutral-400">Completa la información por secciones.</p></div><a href="{{ route('products.index') }}" class="icon-button" aria-label="Cerrar formulario"><i class="bi bi-x-lg"></i></a></div>
    <form action="{{ $action }}" method="POST" enctype="multipart/form-data" class="form-panel">
        @csrf @if($editing) @method('PUT') @endif
        <section class="form-section"><h2 class="text-lg font-semibold text-white">Información básica</h2><p>Identifica el producto y asígnalo a un proveedor.</p><div class="mt-5 grid gap-5 sm:grid-cols-2">
            <div><label for="name" class="field-label">Nombre <span class="required">*</span></label><input id="name" name="name" value="{{ old('name', $product?->name) }}" required class="field-control" aria-describedby="name-error">@error('name')<p id="name-error" class="field-error">{{ $message }}</p>@enderror</div>
            <div><label for="sku" class="field-label">SKU</label><input id="sku" name="sku" value="{{ old('sku', $product?->sku) }}" class="field-control" aria-describedby="sku-error">@error('sku')<p id="sku-error" class="field-error">{{ $message }}</p>@enderror</div>
            <div><label for="category_id" class="field-label">Categoría <span class="required">*</span></label><select id="category_id" name="category_id" required class="field-control">@foreach($categories as $categoryOption)<option value="{{ $categoryOption->id }}" @selected(old('category_id', $product?->category_id) == $categoryOption->id)>{{ $categoryOption->name }}</option>@endforeach</select>@error('category_id')<p class="field-error">{{ $message }}</p>@enderror</div>
            <div><label for="supplier_id" class="field-label">Proveedor <span class="required">*</span></label><select id="supplier_id" name="supplier_id" required class="field-control"><option value="">Seleccionar proveedor</option>@foreach($suppliers as $supplier)<option value="{{ $supplier->id }}" @selected(old('supplier_id', $product?->supplier_id) == $supplier->id)>{{ $supplier->name }}</option>@endforeach</select>@error('supplier_id')<p class="field-error">{{ $message }}</p>@enderror</div>
        </div></section>
        <section class="form-section"><h2 class="text-lg font-semibold text-white">Precio e inventario</h2><p>Define los valores que se usarán en compras, ventas y stock.</p><div class="mt-5 grid gap-5 sm:grid-cols-3">
            <div><label for="purchase_price" class="field-label">Precio de compra <span class="required">*</span></label><input id="purchase_price" type="number" step="0.01" min="0" name="purchase_price" value="{{ old('purchase_price', $product?->purchase_price) }}" required class="field-control">@error('purchase_price')<p class="field-error">{{ $message }}</p>@enderror</div>
            <div><label for="sale_price" class="field-label">Precio de venta <span class="required">*</span></label><input id="sale_price" type="number" step="0.01" min="0" name="sale_price" value="{{ old('sale_price', $product?->sale_price) }}" required class="field-control">@error('sale_price')<p class="field-error">{{ $message }}</p>@enderror</div>
            <div><label for="initial_stock" class="field-label">Stock inicial</label><input id="initial_stock" type="number" min="0" name="initial_stock" value="{{ old('initial_stock', $product?->initial_stock ?? 0) }}" class="field-control">@error('initial_stock')<p class="field-error">{{ $message }}</p>@enderror</div>
        </div></section>
        <section class="form-section"><h2 class="text-lg font-semibold text-white">Detalles adicionales</h2><p>Agrega una descripción o una imagen para facilitar la gestión.</p><div class="mt-5 space-y-5"><div><label for="description" class="field-label">Descripción</label><textarea id="description" name="description" rows="4" class="field-control py-3">{{ old('description', $product?->description) }}</textarea>@error('description')<p class="field-error">{{ $message }}</p>@enderror</div><div><label for="image" class="field-label">Imagen</label><input id="image" type="file" name="image" accept="image/*" class="field-control py-2">@error('image')<p class="field-error">{{ $message }}</p>@enderror</div></div></section>
        <div class="form-actions"><a href="{{ route('products.index') }}" class="btn-secondary">Cancelar</a><button type="submit" class="btn-primary">{{ $editing ? 'Guardar cambios' : 'Guardar producto' }}</button></div>
    </form>
</div>
